DDL - DATA DEFINITION LANGUAGE

--CREATE TABLE 
CREATE TABLE minha_tabela (
    id        NUMBER
        GENERATED BY DEFAULT AS IDENTITY
    PRIMARY KEY,
    descricao VARCHAR2(30)
);

CREATE TABLE minha_segunda_tb (
    id        NUMBER PRIMARY KEY,
    descricao VARCHAR(30)
); 

SELECT * FROM minha_segunda_tb;
delete minha_segunda_tb

INSERT INTO minha_segunda_tb (id,DESCRICAO) VALUES (sq_minha_tab.nextval,'Segundo insert');
INSERT INTO minha_segunda_tb (id,DESCRICAO) VALUES (2,'Segundo insert');
INSERT INTO minha_segunda_tb (id,DESCRICAO) VALUES (3,'Terceiro insert');
commit;


CREATE SEQUENCE

create sequence sq_minha_tab;
ALTER TABLE
CREATE INDEX
CREATE CONSTRAINTS
ALTER CONSTRAINTS